---
# tasks file for sing_box_config
- name: verify sing_box_state_dir exists
  ansible.builtin.stat:
    path: "{{ sing_box_state_dir }}"
  register: sing_box_state_dir_stat
  failed_when:
    - not sing_box_state_dir_stat.stat.exists
    - not sing_box_state_dir_stat.stat.isdir

- name: ensure python3-venv packages is installed
  ansible.builtin.package:
    name:
      - python3-packaging
      - python3-venv
    state: present

- name: install sing-box-config from dist_wheel
  when: sing_box_pip_install_source == 'local'
  ansible.builtin.import_tasks: dist_wheel.yaml

- name: install sing-box-config from PyPI
  when: sing_box_pip_install_source in ['pypi', 'testpypi']
  ansible.builtin.pip:
    name: sing-box-config
    state: latest
    virtualenv: "{{ sing_box_state_venv_dir }}"
    virtualenv_command: python3 -m venv
    extra_args: "{{ sing_box_pip_extra_args[sing_box_pip_install_source] }}"
  notify:
    - ensure sing-box working directory ownership

- name: ensure sing-box-config configuration and service state
  vars:
    # roles/sing_box_config/templates/base.json.j2
    base_template: base.json.j2
    base_basename: "{{ base_template | ansible.builtin.basename | ansible.builtin.splitext | first }}"
    base_dest: "{{ [sing_box_state_config_dir, base_basename] | ansible.builtin.path_join }}"
    base_dest_local: "{{ [sing_box_local_config_dir, base_basename] | ansible.builtin.path_join }}"
    # roles/sing_box_config/templates/subscriptions.json.j2
    subscriptions_template: subscriptions.json.j2
    subscriptions_basename: "{{ subscriptions_template | ansible.builtin.basename | ansible.builtin.splitext | first }}"
    subscriptions_dest: "{{ [sing_box_state_config_dir, subscriptions_basename] | ansible.builtin.path_join }}"
    subscriptions_dest_local: "{{ [sing_box_local_config_dir, subscriptions_basename] | ansible.builtin.path_join }}"
  ansible.builtin.import_tasks: state.yaml

- name: deploy sing-box-liveness-probe.service
  when: sing_box_liveness_probe_deploy | ansible.builtin.bool
  ansible.builtin.import_tasks: liveness_probe.yaml
