---
# handlers file for sing_box_tproxy
- name: systemctl daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: systemctl restart nftables.service
  ansible.builtin.systemd_service:
    name: nftables.service
    state: restarted

- name: restart sing-box-tproxy-routing.service
  ansible.builtin.systemd_service:
    name: sing-box-tproxy-routing.service
    state: restarted
