---
# [sing-box outbounds[]]
sing_box_region_regex:
  SG: "新加坡|坡|狮城|SG|Singapore"
  HK: "港|HK|Hong Kong"
  JP: "日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan"
  TW: "台|新北|彰化|TW|Taiwan"
  US: "美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"
  EU: "(Belgium|比利时)|(Finland|Helsinki|芬兰|赫尔辛基)|\\bDE[U]?\\b|Germany|法兰克福|德(国|意志)|中德|^德$|\\bD[N]?K\\b|Denmark|丹麦|\\bES[P]?\\b|Spain|西班牙|\\bFR[A]?\\b|France|Paris|法国|巴黎|\\bIS[L]?\\b|Iceland|冰岛|\\bNL[D]?\\b|Netherlands|荷兰|阿姆斯特丹|\\bUK\\b|\\bGB[R]?\\b|England|United.*?Kingdom|London|英国|[^-]英|伦敦|(Ireland|Dublin|爱尔兰|都柏林)|(Italy|Milan|意大利|米兰)|(Switzerland|Zurich|瑞士|苏黎世)|(希腊|Greece)|(挪威|Norway)"
  KR: "KR|Korea|KOR|首尔|韩|韓"
