---
# defaults file for singbox_tproxy
# https://wiki.debian.org/SystemGroups#Groups_with_an_associated_user
# proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
proxy_user:
  name: proxy
  uid: 13
  home: /bin
  shell: /usr/sbin/nologin
proxy_group:
  name: proxy
  gid: 13

# 对应 sing-box 中 type = tproxy 的 inbounds
singbox_tproxy_port: 7895

# ip -f inet rule add fwmark $PROXY_MARK lookup $PROXY_ROUTE_TABLE
# ip -f inet route add local default dev $INTERFACE table $PROXY_ROUTE_TABLE
# echo "224 singbox_tproxy" | sudo tee /etc/iproute2/rt_tables.d/singbox_tproxy.conf >/dev/null
singbox_proxy_route_table: 224
singbox_proxy_mark: 224

# 对应 sing-box 配置项 route.default_mark
singbox_route_default_mark: 225

singbox_etc_dir: /etc/sing-box
singbox_log_dir: /var/log/sing-box
singbox_state_dir: /var/lib/sing-box

singbox_templates:
  - etc/iproute2/rt_tables.d/singbox_tproxy.conf.j2
  - etc/netplan/99-singbox_tproxy.yaml.j2
  - etc/nftables.conf.j2
  - etc/systemd/system/sing-box.service.j2
  - etc/systemd/system/sing-box-reload.path.j2
  - etc/systemd/system/sing-box-reload.service.j2
