# https://pdm-project.org/en/latest/usage/publish/
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: ~

jobs:
  build-n-push:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sing-box-config

    permissions:
      # This permission is needed for private repositories.
      # contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11

      - name: Build a binary wheel and a source tarball
        run: pdm build -v

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
