# https://pdm-project.org/en/latest/usage/publish/
on:
  push:
    tags:
      - "**"
  workflow_dispatch: ~

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sing-box-config
    permissions:
      # # This permission is needed for private repositories.
      # contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11

      - name: Publish package distributions to PyPI
        run: |
          git status
          pdm publish -v
